export const GET_STARS_REPOSITORY = '[HOME] GET_STARS_REPOSITORY';
export const GET_FORKS_REPOSITORY = '[HOME] GET_FORKS_REPOSITORY';
export const GET_WATCHS_REPOSITORY = '[HOME] GET_WATCHS_REPOSITORY';
export const FAILED_GITHUB_API = '[HOME] FAILED_GITHUB_API';
