export const GET_STARS_REPOSITORE = '[HOME] GET_STARS_REPOSITORE';
export const GET_FORKS_REPOSITORE = '[HOME] GET_FORKS_REPOSITORE';
export const GET_WATCHS_REPOSITORE = '[HOME] GET_WATCHS_REPOSITORE';
export const FAILED_GITHUB_API = '[HOME] FAILED_GITHUB_API';
